name: build code

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-14

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Show system info
              run: |
                  uname -a
