name: build code

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
              uses: carlosperate/arm-none-eabi-gcc-action@v1

            - name: Check toolchain
              run: arm-none-eabi-gcc --version

            - name: Build
              run: make

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: |
                      Source/build/*.hex
                      Source/build/*.bin
                      Source/build/*.map
